DROP SCHEMA IF EXISTS `RUTAS`;
-- SCHEMA RUTAS--

CREATE SCHEMA IF NOT EXISTS `RUTAS` DEFAULT CHARACTER SET utf8mb4;
USE `RUTAS`;

CREATE TABLE IF NOT EXISTS `EMPRESA`(
    `idEmpresa` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(255),
    `domicilio` VARCHAR(255),
    `telefono` VARCHAR(55),
    `cuit` VARCHAR(55),
    `codigoPostal` VARCHAR(55),
    `nombreRepresentante` VARCHAR(255),
    `apellidoRepresentante` VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `CONCESION`(
    `idConcesion` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `fechaInicio` DATE,
    `fechaFinalizacion` DATE,
    `idEmpresa` INT NOT NULL,
    CONSTRAINT `FK_CONCESION_EMPRESA` FOREIGN KEY (`idEmpresa`) REFERENCES `EMPRESA` (`idEmpresa`) ON DELETE NO ACTION ON UPDATE NO ACTION 
);

CREATE TABLE IF NOT EXISTS `CATEGORIA`(
    `idCategoria` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `RUTA`(
    `idRuta` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idCategoria` INT,
    `nombre` VARCHAR(255),
    CONSTRAINT `FK_RUTA_CATEGORIA` FOREIGN KEY (`idCategoria`) REFERENCES `CATEGORIA`(`idCategoria`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `LOCALIDAD`(
    `idLocalidad` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(255),
    `codigoPostal` VARCHAR(50),
    `provincia` VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `TRAMO`(
    `idTramo` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idRuta` INT NOT NULL,
    `idLocalidadInicio` INT NOT NULL,
    `idLocalidadFin` INT NOT NULL,
    `kmInicio` VARCHAR(50),
    `kmFIn` VARCHAR(50),
    CONSTRAINT `FK_TRAMO_RUTA` FOREIGN KEY (`idRuta`) REFERENCES `RUTA` (`idRuta`)  ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_TRAMO_LOCALIDAD_INICIO` FOREIGN KEY (`idLocalidadInicio`) REFERENCES `LOCALIDAD` (`idLocalidad`)  ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_TRAMO_LOCALIDAD_FIN` FOREIGN KEY (`idLocalidadFin`) REFERENCES `LOCALIDAD` (`idLocalidad`)  ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `CONFLUENCIA`(
    `idConfluencia` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idTramoInicio` INT NOT NULL,
    `idTramoFin` INT NOT NULL,
    `tipo` VARCHAR(255),
    `kmDeConfluencia` VARCHAR(255),
    CONSTRAINT `FK_CONFLUENCIA_TRAMO_INICIO` FOREIGN KEY (`idTramoInicio`) REFERENCES `TRAMO` (`idTramo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_CONFLUENCIA_TRAMO_FIN` FOREIGN KEY (`idTramoFin`) REFERENCES `TRAMO` (`idTramo`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `OBRA`(
    `idObra` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idTramo` INT NOT NULL,
    `idConcesion` INT NOT NULL,
    `estado` VARCHAR(255),
    `montoProyectado` DECIMAL,
    `montoEjecutado` DECIMAL,
    CONSTRAINT `FK_OBRA_TRAMO` FOREIGN KEY (`idTramo`) REFERENCES `TRAMO` (`idTramo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_OBRA_CONCESION` FOREIGN KEY (`idConcesion`) REFERENCES `CONCESION` (`idConcesion`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `ESTADO`(
    `idEstado` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `tipoDeRuta` VARCHAR(255),
    `tipoDeSenializacion` VARCHAR(255),
    `vejez` DATE,
    `idRuta` INT NOT NULL,
    CONSTRAINT `FK_ESTADO_RUTA` FOREIGN KEY (`idRuta`) REFERENCES `RUTA` (`idRuta`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `CONCESIONRUTA`(
    `idConcesionRuta` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idRuta` INT NOT NULL,
    `idConcesion` INT NOT NULL,
    CONSTRAINT `FK_CONCESIONRUTA_RUTA` FOREIGN KEY (`idRuta`) REFERENCES `RUTA` (`idRuta`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_CONCESIONRUTA_CONCESION` FOREIGN KEY (`idConcesion`) REFERENCES `CONCESION` (`idConcesion`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PEAJE`(
    `idPeaje` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idConcesionRuta` INT NOT NULL,
    `precio` DECIMAL,
    `kmUbicacion` VARCHAR(50),
    CONSTRAINT `FK_PEAJE_CONCESIONRUTA` FOREIGN KEY (`idConcesionRuta`) REFERENCES `CONCESIONRUTA` (`idConcesionRuta`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
