DROP SCHEMA IF EXISTS `MUDANZA`;
-- SCHEMA MUDANZA--

CREATE SCHEMA IF NOT EXISTS `MUDANZA` DEFAULT CHARACTER SET utf8mb4;
USE `MUDANZA`;

CREATE TABLE IF NOT EXISTS `LOCALIDAD`(
    `idLocalidad` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(255) NOT NULL,
    `codigoPostal` VARCHAR(50) NOT NULL,
    `provincia` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `CLIENTE`(
    `idCliente` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(50) NOT NULL,
    `apellido` VARCHAR(50) NOT NULL,
    `codigoCliente` VARCHAR(50) NOT NULL,
    `nif` VARCHAR(50) NOT NULL,
    `direccion` VARCHAR(255),
    `telefono` VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS `RECARGO`(
    `idRecargo` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `recargo500a750` FLOAT NOT NULL DEFAULT 1.10,
    `recargoMasDe750` FLOAT NOT NULL DEFAULT 1.15
);

CREATE TABLE IF NOT EXISTS `EMPRESA`(
    `idEmpresa` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idRecargo` INT NOT NULL,
    `nombre` VARCHAR(50) NOT NULL,
    `direccion` VARCHAR(255),
    `telefono` VARCHAR(50) NOT NULL,
    CONSTRAINT `FK_EMPRESA_RECARGO` FOREIGN KEY (`idRecargo`) REFERENCES `RECARGO` (`idRecargo`) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE IF NOT EXISTS `EMPLEADO`(
    `idEmpleado` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(50) NOT NULL,
    `apellido` VARCHAR(50) NOT NULL,
    `nif` VARCHAR(50) NOT NULL,
    `telefono` VARCHAR(50) NOT NULL,
    `telefonoEmpresa` VARCHAR(50) NOT NULL,
    `tipo` VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS `EMPLEADOEMPRESA`(
    `idEmpleadoEmpresa` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idEmpleado` INT NOT NULL,
    `idEmpresa` INT NOT NULL,
    `fechaInicioContratacion` DATE NOT NULL,
    `fechaFinContratacion` DATE NOT NULL,
    `sueldo` DOUBLE NOT NULL,
    CONSTRAINT `FK_EMPLEADOEMPRESA_EMPLEADO` FOREIGN KEY (`idEmpleado`) REFERENCES `EMPLEADO` (`idEmpleado`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_EMPLEADOEMPRESA_EMPRESA` FOREIGN KEY (`idEmpresa`) REFERENCES `EMPRESA` (`idEmpresa`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `SERVICIO`(
    `idServicio` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(255),
    `rangoPeso` VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS `EMPRESASERVICIOLOCALIDAD`(
    `idEmpresaServicioLocalidad` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idServicio` INT NOT NULL,
    `idLocalidad` INT NOT NULL,
    `idEmpresa` INT NOT NULL,
    `precioHora` DOUBLE NOT NULL,
    CONSTRAINT `FK_PRECIOHORA_SERVICIO` FOREIGN KEY (`idServicio`) REFERENCES `SERVICIO` (`idServicio`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_PRECIOHORA_LOCALIDAD` FOREIGN KEY (`idLocalidad`) REFERENCES `LOCALIDAD` (`idLocalidad`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_PRECIOHORA_EMPRESA` FOREIGN KEY (`idEmpresa`) REFERENCES `EMPRESA` (`idEmpresa`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `FACTURA`(
    `idFactura` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idEmpresa` INT DEFAULT NULL,
    `idCliente` INT DEFAULT NULL,
    `numero` VARCHAR(255) DEFAULT NULL,
    `montoPagado` DECIMAL(10,0) DEFAULT NULL,
    `estado` VARCHAR(255),
    `fecha` DATE DEFAULT NULL,
    CONSTRAINT `FK_FACTURA_CLIENTE` FOREIGN KEY (`idCliente`) REFERENCES `CLIENTE` (`idCliente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_FACTURA_EMPRESA` FOREIGN KEY (`idEmpresa`) REFERENCES `EMPRESA` (`idEmpresa`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `DETALLEMUDANZA`(
    `idDetalleMudanza` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `fechaMudanza` DATE NOT NULL,
    `estadoMudanza` VARCHAR(255) NOT NULL,
    `duracion` TIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `EMPLEADOASIGNADO`(
    `idEmpleadoAsignado` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idDetalleMudanza` INT NOT NULL,
    `idEmpleado` INT NOT NULL,
    CONSTRAINT `FK_EMPLEADOASIGNADO_DETALLEMUDANZA` FOREIGN KEY (`idDetalleMudanza`) REFERENCES `DETALLEMUDANZA` (`idDetalleMudanza`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_EMPLEADOASIGNADO_EMPLEADO` FOREIGN KEY (`idEmpleado`) REFERENCES `EMPLEADO` (`idEmpleado`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `SOLICITUD`(
    `idSolicitud` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idDetalleMudanza` INT,
    `idCliente` INT NOT NULL,
    `idEmpresaServicioLocalidad` INT NOT NULL,
    `idLocalidadOrigen` INT NOT NULL,
    `idLocalidadDestino` INT NOT NULL,
    `direccionOrigen` VARCHAR(255),
    `direccionDestino` VARCHAR(255),
    `codigoSolicitud` VARCHAR(50) NOT NULL,
    `estadoSolicitud` VARCHAR(255) NOT NULL,
    `fechaSolicitud` DATE NOT NULL,
    `fechaResolucion` DATE,
    `precioTotal` DECIMAL DEFAULT 0,
    CONSTRAINT `FK_SOLICITUD_DETALLEMUDANZA` FOREIGN KEY (`idDetalleMudanza`) REFERENCES `DETALLEMUDANZA` (`idDetalleMudanza`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_SOLICITUD_CLIENTE` FOREIGN KEY (`idCliente`) REFERENCES `CLIENTE` (`idCliente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_SOLICITUD_EMPRESASERVICIOLOCALIDAD` FOREIGN KEY (`idEmpresaServicioLocalidad`) REFERENCES `EMPRESASERVICIOLOCALIDAD` (`idEmpresaServicioLocalidad`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_SOLICITUD_LOCALIDAD_ORIGEN` FOREIGN KEY (`idLocalidadOrigen`) REFERENCES `LOCALIDAD` (`idLocalidad`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_SOLICITUD_LOCALIDAD_DESTINO` FOREIGN KEY (`idLocalidadDestino`) REFERENCES `LOCALIDAD` (`idLocalidad`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
