DROP SCHEMA IF EXISTS `HIPERAUTO`;
-- -----------------------------------------------------
-- Schema HIPERAUTO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HIPERAUTO` DEFAULT CHARACTER SET utf8mb4;

USE `HIPERAUTO`;

CREATE TABLE IF NOT EXISTS `PAIS`(
    `idPais` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS `SUCURSAL`(
    `idSucursal` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idPais` INT NOT NULL,
    `codigo` VARCHAR(50) NOT NULL,
    `nombre` VARCHAR(50) NOT NULL,
    `direccion` VARCHAR(255) NOT NULL,
    `ciudad` VARCHAR(200) NOT NULL,
    CONSTRAINT `FK_SUCURSAL_PAIS` FOREIGN KEY (`idPais`) REFERENCES `PAIS` (`idPais`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PIEZA`(
    `idPieza` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(200) NOT NULL,
    `codPieza` VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS `PEDIDO`(
    `idPedido` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idSucursal` INT NOT NULL,
    `codigo` VARCHAR(50) NOT NULL,
    `fecha` DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT `FK_PEDIDO_SUCURSAL`FOREIGN KEY (`idSucursal`) REFERENCES `SUCURSAL` (`idSucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE IF NOT EXISTS `STOCK`(
    `idStock` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `cantidad` INT NOT NULL DEFAULT 0,
    `idSucursal` INT NOT NULL,
    `idPieza` INT NOT NULL,
    `cantMinima` INT NOT NULL DEFAULT 0,
    CONSTRAINT `FK_STOCK_SUCURSAL` FOREIGN KEY (`idSucursal`) REFERENCES `SUCURSAL` (`idSucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_STOCK_PIEZA` FOREIGN KEY (`idPieza`) REFERENCES `PIEZA` (`idPieza`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `CONCESIONARIO`(
    `idConcesionario` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idPais` INT NOT NULL,
    `idSucursal` INT NOT NULL,
    `codigo` VARCHAR(50) NOT NULL,
    `nombre` VARCHAR(50) NOT NULL,
    `direccion` VARCHAR(255) NOT NULL,
    `ciudad` VARCHAR(200) NOT NULL,
    CONSTRAINT `FK_CONCESIONARIO_PAIS` FOREIGN KEY (`idPais`) REFERENCES `PAIS` (`idPais`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_CONCESIONARIO_SUCURSAL` FOREIGN KEY (`idSucursal`) REFERENCES `SUCURSAL` (`idSucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `DETALLE_PEDIDO`(
    `idDetallePedido` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idPedido` INT NOT NULL,
    `idPieza` INT NOT NULL,
    `cantPiezas` INT NOT NULL DEFAULT 0,
    CONSTRAINT `FK_DETALLE_PEDIDO_PEDIDO` FOREIGN KEY (`idPedido`) REFERENCES `PEDIDO` (`idPedido`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_DETALLE_PEDIDO_PIEZA` FOREIGN KEY (`idPieza`) REFERENCES `PIEZA` (`idPieza`) ON DELETE NO ACTION ON UPDATE NO ACTION
    
);









