DROP SCHEMA IF EXISTS `CENTRAL_ELECTRICA`;
-- -----------------------------------------------------
-- CENTRAL_ELECTRICA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CENTRAL_ELECTRICA` DEFAULT CHARACTER SET utf8mb4;
USE `CENTRAL_ELECTRICA`;

CREATE TABLE IF NOT EXISTS `ESTACION_PRIMARIA` (
    `idEstacion` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(255) NOT NULL,
    `cantTransformadoresAltaTension` INT NOT NULL,
    `cantTransformadoresBajaTension` INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `RED_DISTRIBUCION` (
    `idRed` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idEstacion` INT NOT NULL,
    `numeroRed` VARCHAR(255) NOT NULL,
    CONSTRAINT `FK_RED_DISTRIBUCION_ESTACION_PRIMARIA` FOREIGN KEY (`idEstacion`) REFERENCES `ESTACION_PRIMARIA` (`idEstacion`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `LINEA` (
    `idLinea` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idRed` INT NOT NULL,
    `nombre` VARCHAR(255),
    `longitud` DOUBLE NOT NULL,
    CONSTRAINT `FK_LINEA_RED_DISTRIBUCION` FOREIGN KEY (`idRed`) REFERENCES `RED_DISTRIBUCION` (`idRed`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `SUBESTACION` (
    `idSubestacion` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idLinea` INT NOT NULL,
    `nombre` VARCHAR(255) NULL DEFAULT NULL,
    CONSTRAINT `FK_SUBESTACION_LINEA` FOREIGN KEY (`idLinea`) REFERENCES `LINEA` (`idLinea`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PROVINCIA` (
    `idProvincia` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(255) NOT NULL,
    `codigo` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `ZONA_SERVICIO` (
    `idZona` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idProvincia` INT NOT NULL,
    `nombre` VARCHAR(255) NULL DEFAULT NULL,
    CONSTRAINT `FK_ZONA_SERVICIO_PROVINCIA` FOREIGN KEY (`idProvincia`) REFERENCES `PROVINCIA` (`idProvincia`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `ABASTECIMIENTO` (
    `idAbastecimiento` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idSubestacion` INT NOT NULL,
    `idZona` INT NOT NULL,
    `cantidadEnergia` DOUBLE NOT NULL,
    CONSTRAINT `FK_ABASTECIMIENTO_SUBESTACION` FOREIGN KEY (`idSubestacion`) REFERENCES `SUBESTACION` (`idSubestacion`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_ABASTECIMIENTO_ZONA_SERVICIO` FOREIGN KEY (`idZona`) REFERENCES `ZONA_SERVICIO` (`idZona`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PRODUCTOR` (
    `idProductor` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `CENTRAL` (
    `idCentral` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idProductor` INT NOT NULL,
    `nombre` VARCHAR(255) NOT NULL,
    `prodMedia` DOUBLE NOT NULL,
    `prodMax` DOUBLE NOT NULL,
    `fechaConstruccion` DATE NULL DEFAULT NULL,
    CONSTRAINT `FK_CENTRAL_PRODUCTOR` FOREIGN KEY (`idProductor`) REFERENCES `PRODUCTOR` (`idProductor`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `ENTREGA_ENERGIA` (
    `idEntrega` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idCentral` INT NOT NULL,
    `idEstacion` INT NOT NULL,
    `cantidadEnergia` DOUBLE NULL DEFAULT NULL,
    CONSTRAINT `FK_ENTREGA_ENERGIA_CENTRAL` FOREIGN KEY (`idCentral`) REFERENCES `CENTRAL` (`idCentral`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_ENTREGA_ENERGIA_ESTACION` FOREIGN KEY (`idEstacion`) REFERENCES `ESTACION_PRIMARIA` (`idEstacion`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `HIDROELECTRICA` (
  `idHidroelectrica` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `idCentral` INT NOT NULL,
  `capacidadVolMax` DOUBLE NULL DEFAULT NULL,
  `cantidadTurbinas` INT NULL DEFAULT NULL,
  `ocupacion` DOUBLE NULL DEFAULT NULL,
  CONSTRAINT `FK_HIDROELECTRICA_CENTRAL` FOREIGN KEY (`idCentral`) REFERENCES `CENTRAL` (`idCentral`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `INTERCAMBIO` (
    `idIntercambio` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idRedEnvio` INT NOT NULL,
    `idRedRecibida` INT NOT NULL,
    `cantEnergia` DOUBLE NOT NULL,
    CONSTRAINT `FK_INTERCAMBIO_RED_ENVIO` FOREIGN KEY (`idRedEnvio`) REFERENCES `RED_DISTRIBUCION` (`idRed`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_INTERCAMBIO_RED_RECIBIDA` FOREIGN KEY (`idRedRecibida`) REFERENCES `RED_DISTRIBUCION` (`idRed`) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE IF NOT EXISTS `NUCLEAR` (
    `idNuclear` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idCentral` INT NOT NULL,
    `volPlutonioConsumido` DOUBLE NULL DEFAULT NULL,
    `prodResiduos` DOUBLE NULL DEFAULT NULL,
    `cantidadReactores` INT NULL DEFAULT NULL,
    CONSTRAINT `FK_NUCLEAR_CENTRAL` FOREIGN KEY (`idCentral`) REFERENCES `CENTRAL` (`idCentral`) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE IF NOT EXISTS `TRANSPORTISTA` (
    `idTransportista` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Nombre` VARCHAR(255) NOT NULL,
    `matricula` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `SUMINISTRADOR` (
    `idSuministrador` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `pais` VARCHAR(255) NOT NULL,
    `nombre` VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS `PORTE` (
    `idPorte` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idTransportista` INT NOT NULL,
    `idSuministrador` INT NOT NULL,
    `idNuclear` INT NOT NULL,
    `cantPlutonio` DOUBLE NOT NULL,
    `fecha` DATE,
    CONSTRAINT `FK_PORTE_TRANSPORTISTA` FOREIGN KEY (`idTransportista`) REFERENCES `TRANSPORTISTA` (`idTransportista`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_PORTE_SUMINISTRADOR` FOREIGN KEY (`idSuministrador`) REFERENCES `SUMINISTRADOR` (`idSuministrador`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_PORTE_NUCLEAR` FOREIGN KEY (`idNuclear`) REFERENCES `NUCLEAR` (`idNuclear`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PROPIETARIO` (
    `idPropietario` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `nombre` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `TIPO_PANELES` (
    `idTipo` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `descripcion` VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS `SOLAR` (
    `idSolar` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idCentral` INT NOT NULL,
    `idTipoPaneles` INT NOT NULL,
    `superficiePaneles` DOUBLE NULL DEFAULT NULL,
    `mediaHorasSolares` DOUBLE NULL DEFAULT NULL,
    CONSTRAINT `FK_SOLAR_CENTRAL` FOREIGN KEY (`idCentral`) REFERENCES `CENTRAL` (`idCentral`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_SOLAR_TIPO_PANELES` FOREIGN KEY (`idTipoPaneles`) REFERENCES `TIPO_PANELES` (`idTipo`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `TERMICA` (
    `idTermica` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idCentral` INT NOT NULL,
    `volCarbonProducido` DOUBLE NULL DEFAULT NULL,
    `volEmisiones` DOUBLE NULL DEFAULT NULL,
    `cantidadHornos` INT NULL DEFAULT NULL,
    CONSTRAINT `FK_TERMICA_CENTRAL` FOREIGN KEY (`idCentral`) REFERENCES `CENTRAL` (`idCentral`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PROPIEDAD` (
    `idPropiedad` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idPropietario` INT NOT NULL,
    `idRed` INT NOT NULL,
    CONSTRAINT `FK_PROPIEDAD_PROPIETARIO` FOREIGN KEY (`idPropietario`) REFERENCES `PROPIETARIO` (`idPropietario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `FK_PROPIEDAD__RED_DISTRIBUCION` FOREIGN KEY (`idRed`) REFERENCES `RED_DISTRIBUCION` (`idRed`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
